# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'madFeedback' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for madFeedback
  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  target 'madFeedback-tvOSTests' do

    inherit! :search_paths
    # Pods for testing
  end

  target 'madFeedbackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'madFeedback-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for madFeedback-tvOS
  pod 'Firebase/Firestore'
  


end
